name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4

  release:
    runs-on: ubuntu-latest

    needs: validate

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_hyperaUsername: ${{ secrets.HYPERA_USERNAME }}
          ORG_GRADLE_PROJECT_hyperaPassword: ${{ secrets.HYPERA_PASSWORD }}